name: Test Translation Action

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 번역 액션 실행
      - name: Run translation action
        uses: ./ # 현재 레포지토리의 액션을 사용
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          translations-dir: 'test/translations'
          source-lang: 'ko'
          target-lang: 'en'
          model: 'gpt-4o'
          git-user-name: 'github-actions[bot]'
          git-user-email: 'github-actions[bot]@users.noreply.github.com'
          temperature: 0.7
          max-tokens: 2000
